### ISSUE TITLE
.

### ISSUE THREAD

**Issue by farbodrashidi** [FreedomPrevails/JSMTProxy#22]
.

**Comment by masterprogrammer513** [comment]
This is not issue please post problem in this section.
IP ban is meaning block user IP from connecting to server.

**Comment by pharbod** [comment]
well, to be honest you're definition of IP ban is not true! its baning server IP so users can't connect to it. and I don't know how you don't see this as an issue! what issue can bigger if the government can find my server via protocol headers and ban it? and stop me from using the server?
it's a matter of security and privacy. and there's no place that have wrote or speak about this topic, so we need some clarification on this.

**Comment by VahidN** [comment]
All communications here are encrypted using the AES algo. So it's not possible to detect the protocol headers (or anything) from it unless first decrypting it using your server's `secret key`.
So don't worry about it.
But … if you publish your server's info publicly in the proxy advertising channels, there are a lot of bots there to monitor those info and disable them automatically.
