### ISSUE TITLE
HI.I BUY A NEW SERVER

### ISSUE THREAD

**Issue by alirezashahrokhi** [FreedomPrevails/JSMTProxy#4]
hi dears i buy new server and by ssh run all your code
when i change port my server not loaded and need to reload
may you help me config port?for new server for run this lovely mtproto?
i need 0 to 100
sorry for my bad english

**Comment by alirezashahrokhi** [comment]
i sucssefully config
.but how to create ad(chanel adress)?i proxy?for support?

**Comment by yalpanian** [comment]
look at this : https://github.com/FreedomPrevails/JSMTProxy/issues/1

> dadash fahmidi chejurie be manam begu

telegram : @mikrotik
